services:
  app:
    build: .
    container_name: erpContracts_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - /var/www/html/node_modules
    ports:
      - "8000:8000"
      - "5173:5173"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: erpContracts_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: erpContracts
      MYSQL_USER: erpContracts
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: erpContracts_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_USER: erpContracts
      PMA_PASSWORD: secret
    ports:
      - "8002:80"
    depends_on:
      - db

volumes:
  dbdata: